### ISSUE TITLE
compiling error?

### ISSUE THREAD

**Issue by luciouskami** [peq/wurst4vscode#13]
After I typed "wurst: Run a Wurst map."  and select a map then pressed enter,Vsccode showed: 
There was a Wurst bug, while compiling the map: 'other' has different root

**Comment by luciouskami** [comment]
because i'm a newbie,i don't know how to slove it

**Comment by peq** [comment]
Hi,

I would need the map code to debug this.

Can you send me the code? (Peter.peq@gmail.com)

**Comment by luciouskami** [comment]
@peq 
just the hello word
```
 package Hello

 init
     print("Hello Wurst")
```

**Comment by peq** [comment]
Hmm, strange. Is there some other code in the map? Can you try with a new,
empty map?

On Dec 15, 2016 09:37, "神话" <notifications@github.com> wrote:

@peq <https://github.com/peq>
just the hello word

 package Hello

 init
     print("Hello Wurst")

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/peq/wurst4vscode/issues/13#issuecomment-267269230>, or mute
the thread

**Comment by luciouskami** [comment]
@peq 
Yes,I used [YDWE](https://github.com/actboy168/YDWE) to create a new ,empty map.
And i've turnned off the "smart code inject",so i'm sure the file "war3map.j" is clear.
![2](https://cloud.githubusercontent.com/assets/10268785/21217244/30e6ec56-c2e6-11e6-9dae-e989428633fd.jpg)

**Comment by luciouskami** [comment]
![3](https://cloud.githubusercontent.com/assets/10268785/21217946/b3744fda-c2e9-11e6-8520-2b9452184654.jpg)
Is this file correct？

**Comment by Frotty** [comment]
Try not using YDWE to see if it causes the error.
Wurst dependencies should look like this:
C:\Users\Frotty\Documents\GitHub\stdlib2

without quotes and using backslashes (but this depends on your os I believe)

**Comment by luciouskami** [comment]
@Frotty Hmm.I 've used the official WE to create an empty map and the it caused the same error.

**Comment by Frotty** [comment]
Is it a tft map? (.w3x) w3m are not supported.

**Comment by luciouskami** [comment]
Yes,it is.

**Comment by Frotty** [comment]
show your settings.json?
I just tried running my map and it works fine.

**Comment by luciouskami** [comment]
![settinv](https://cloud.githubusercontent.com/assets/10268785/21229714/79756baa-c31d-11e6-9537-2ccb854f28ed.jpg)

**Comment by Frotty** [comment]
Do you get compile errors in vscode before running the map?
Can you zip your project and map and upload it? Maybe it has to do with your locale.

**Comment by luciouskami** [comment]
sure.I'll uoload it.
https://www.dropbox.com/s/he6bt68gq74jy9v/Wurstproject.zip?dl=0

**Comment by Frotty** [comment]
For me wc3 started fine, but your file won't be recognized because it ends in `.Wurst`, which has to be `.wurst` (lowercase) to work. Also change your `Wurst` folder to `wurst`. I never encountered your error though.

Please try running this modified project https://dl.dropboxusercontent.com/u/19704285/WurstprojectModified.zip

If this still doesn't work, please navigate to your wurstscript.jar, open a terminal and do
`java -jar wurstscript.jar --about` and post the version here.

**Comment by luciouskami** [comment]
it still doesn't work.
![version](https://cloud.githubusercontent.com/assets/10268785/21232168/bdbf9e54-c325-11e6-956c-d39f74090c38.jpg)

**Comment by Frotty** [comment]
Okay, it seems to have to do with your paths having different roots (D, E, F)
Try having it all on the same drive.
Also turn on debugMode in your settings.json, like so :
` "wurst.debugMode": true `
And check if the error has additional info with that.

**Comment by luciouskami** [comment]
oh. I'm so sad. I put all files in a same drive,then it still caused the error

**Comment by peq** [comment]
I would need a more precise error message to debug this, as this does not happen on my or Frottys machine. In your `~/AppData/Local/Temp` folder there should be one or more `wurst.log` files which might contain some more information about the error. It would be great if you could share those.

**Comment by luciouskami** [comment]
'''log
java.lang.IllegalArgumentException: 'other' has different root
	at sun.nio.fs.WindowsPath.relativize(Unknown Source)
	at sun.nio.fs.WindowsPath.relativize(Unknown Source)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.getProjectRelativePath(ModelManagerImpl.java:180)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.compileFromJar(ModelManagerImpl.java:391)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.newModel(ModelManagerImpl.java:58)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.updateModel(ModelManagerImpl.java:355)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:504)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.replaceCompilationUnit(ModelManagerImpl.java:441)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnit(ModelManagerImpl.java:480)
	at de.peeeq.wurstio.languageserver.ModelManagerImpl.syncCompilationUnit(ModelManagerImpl.java:450)
	at de.peeeq.wurstio.languageserver.requests.RunMap.compileScript(RunMap.java:195)
	at de.peeeq.wurstio.languageserver.requests.RunMap.execute(RunMap.java:93)
	at de.peeeq.wurstio.languageserver.LanguageWorker.lambda$7(LanguageWorker.java:230)
	at de.peeeq.wurstio.languageserver.LanguageWorker.run(LanguageWorker.java:206)
	at java.lang.Thread.run(Unknown Source)

'''

**Comment by Frotty** [comment]
Please try replacing your current wurstscript.jar with this one.
[wurstscript.zip](https://github.com/peq/wurst4vscode/files/658547/wurstscript.zip)

If it still doesn't work, please paste the last contents of the log before the stacktrace that tell you the `projectPath` and the `fPath` like so:
````
INFO: projectPath: c:\Users\Frotty\Documents\GitHub\EBR
INFO: fPath: c:\Users\Frotty\Documents\GitHub\EBR\wurst\_core\projectiles\Projectile.wurst
````

Or you can paste the complete log here http://hastebin.com/ and post a link.

**Comment by luciouskami** [comment]
projectPath: F:\Wurstproject\wurst
fPath: F:\Wurstproject\wurst\Hello.wurst
link:http://hastebin.com/amujezafeq.tex

**Comment by Frotty** [comment]
Okay the problem is that all your things are now on F: but wurst creates temporary copies of files in window's temp folder, which is on C:

To fix this you could either move your wurst stuff to C: or wait for a patch to fix this soon.

**Comment by luciouskami** [comment]
Okay,thank you

**Comment by luciouskami** [comment]
Good it works fine,after I moved the project folder to C:

**Comment by Frotty** [comment]
Great :) Sorry for the hassle. Feel free to ask further questions.

**Comment by luciouskami** [comment]
It'ok. As my capacity  of C; is so small,I usually put my project folder to other drive.

**Comment by Frotty** [comment]
We are working on a fix. Once pushed you can move it back 👍

**Comment by luciouskami** [comment]
There's no rush. I'm not in a hurr.Still learnning Wurst now.

**Comment by luciouskami** [comment]
fixed
