### ISSUE TITLE
Fix highlighting

### ISSUE THREAD

**Issue by Frotty** [peq/wurst4vscode#15]
![image](https://cloud.githubusercontent.com/assets/1486037/21872116/ef7001b8-d866-11e6-99b0-e00a92d701f5.png)

**Comment by peq** [comment]
The question is: should we fix the highlighting or fix the escaping in
integer literals. Currently it is not compatible with the jass syntax.

**Comment by Frotty** [comment]
![image](https://cloud.githubusercontent.com/assets/1486037/21883757/dfa2deb4-d8b0-11e6-9a28-307035aaf74a.png)

**Comment by peq** [comment]
Because the highlighting is already correct according to Jass syntax rules, I think.

**Comment by Frotty** [comment]
I don't really care. I guess the highlighting is what annoys me right now. Is there a way to receive the same result with correct highlighting by changing the string?
