### ISSUE TITLE
Launch map displays "There was a Wurst bug..." after patching 1.28

### ISSUE THREAD

**Issue by Cokemonkey11** [peq/wurst4vscode#19]
There was a Wurst bug, while compiling the map: C:\Program Files (x86)\Warcaft III\wc3.exe\Maps\wurstTestMap1.w3x (The system cannot find the path specified)

**Comment by Cokemonkey11** [comment]
@peq not sure if you've seen this

**Comment by Cokemonkey11** [comment]
@Frotty I think peter is away. Can you take a look?

**Comment by Frotty** [comment]
Should be fixed. Reopen if not,.
