### ISSUE TITLE
how to inject compiletime objects using vscode without WurstWE?

### ISSUE THREAD

**Issue by vitalexbel** [peq/wurst4vscode#22]
thx

**Comment by Frotty** [comment]
add 
````
-runcompiletimefunctions
-injectobjects
````
to your ```wurst_run.args``` file next to your map.

**Comment by Cokemonkey11** [comment]
@Frotty is this feature documented?

**Comment by Frotty** [comment]
it will be in the new manual

**Comment by peq** [comment]
There will be a new manual?

**Comment by vitalexbel** [comment]
I dont know why but when I run map with VSCode, it injects nothing and ignores compiletime funcs.
`wurst_run.args` contains
```
-runcompiletimefunctions
-injectobjects
```
and is in the same folder as the map.
![screenshot_1](https://user-images.githubusercontent.com/29229748/27844664-47cff580-612d-11e7-9a1a-1120a0d4b183.png)
When I use Sharpcraft World editor and save map with:
![screenshot_1](https://user-images.githubusercontent.com/29229748/27844680-798bb4ec-612d-11e7-8d86-90385b37329f.png)
it adds import and does compiletime funcs. And I dont undesrtand why I can do it with Sharpcraft WE but cant do it with VSCode
